// Copyright (c) 2018, The TurtleCoin Developers
//
// Please see the included LICENSE file for more information.

/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.TurtleToTurtle.BlockChainPayload');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.TurtleToTurtle.TurtleCoin.TurtleBlock');
goog.require('proto.TurtleToTurtle.TurtleCoin.TurtleTransaction');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.TurtleToTurtle.BlockChainPayload = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.TurtleToTurtle.BlockChainPayload.oneofGroups_);
};
goog.inherits(proto.TurtleToTurtle.BlockChainPayload, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.TurtleToTurtle.BlockChainPayload.displayName = 'proto.TurtleToTurtle.BlockChainPayload';
}
/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.TurtleToTurtle.BlockChainPayload.oneofGroups_ = [[2,3]];

/**
 * @enum {number}
 */
proto.TurtleToTurtle.BlockChainPayload.DataCase = {
  DATA_NOT_SET: 0,
  BLOCK: 2,
  TRANSACTION: 3
};

/**
 * @return {proto.TurtleToTurtle.BlockChainPayload.DataCase}
 */
proto.TurtleToTurtle.BlockChainPayload.prototype.getDataCase = function() {
  return /** @type {proto.TurtleToTurtle.BlockChainPayload.DataCase} */(jspb.Message.computeOneofCase(this, proto.TurtleToTurtle.BlockChainPayload.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.TurtleToTurtle.BlockChainPayload.prototype.toObject = function(opt_includeInstance) {
  return proto.TurtleToTurtle.BlockChainPayload.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.TurtleToTurtle.BlockChainPayload} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.TurtleToTurtle.BlockChainPayload.toObject = function(includeInstance, msg) {
  var f, obj = {
    blockchainid: jspb.Message.getFieldWithDefault(msg, 1, 0),
    block: (f = msg.getBlock()) && proto.TurtleToTurtle.TurtleCoin.TurtleBlock.toObject(includeInstance, f),
    transaction: (f = msg.getTransaction()) && proto.TurtleToTurtle.TurtleCoin.TurtleTransaction.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.TurtleToTurtle.BlockChainPayload}
 */
proto.TurtleToTurtle.BlockChainPayload.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.TurtleToTurtle.BlockChainPayload;
  return proto.TurtleToTurtle.BlockChainPayload.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.TurtleToTurtle.BlockChainPayload} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.TurtleToTurtle.BlockChainPayload}
 */
proto.TurtleToTurtle.BlockChainPayload.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setBlockchainid(value);
      break;
    case 2:
      var value = new proto.TurtleToTurtle.TurtleCoin.TurtleBlock;
      reader.readMessage(value,proto.TurtleToTurtle.TurtleCoin.TurtleBlock.deserializeBinaryFromReader);
      msg.setBlock(value);
      break;
    case 3:
      var value = new proto.TurtleToTurtle.TurtleCoin.TurtleTransaction;
      reader.readMessage(value,proto.TurtleToTurtle.TurtleCoin.TurtleTransaction.deserializeBinaryFromReader);
      msg.setTransaction(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.TurtleToTurtle.BlockChainPayload.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.TurtleToTurtle.BlockChainPayload.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.TurtleToTurtle.BlockChainPayload} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.TurtleToTurtle.BlockChainPayload.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBlockchainid();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = message.getBlock();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.TurtleToTurtle.TurtleCoin.TurtleBlock.serializeBinaryToWriter
    );
  }
  f = message.getTransaction();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.TurtleToTurtle.TurtleCoin.TurtleTransaction.serializeBinaryToWriter
    );
  }
};


/**
 * optional uint32 blockChainId = 1;
 * @return {number}
 */
proto.TurtleToTurtle.BlockChainPayload.prototype.getBlockchainid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.TurtleToTurtle.BlockChainPayload.prototype.setBlockchainid = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional TurtleCoin.TurtleBlock block = 2;
 * @return {?proto.TurtleToTurtle.TurtleCoin.TurtleBlock}
 */
proto.TurtleToTurtle.BlockChainPayload.prototype.getBlock = function() {
  return /** @type{?proto.TurtleToTurtle.TurtleCoin.TurtleBlock} */ (
    jspb.Message.getWrapperField(this, proto.TurtleToTurtle.TurtleCoin.TurtleBlock, 2));
};


/** @param {?proto.TurtleToTurtle.TurtleCoin.TurtleBlock|undefined} value */
proto.TurtleToTurtle.BlockChainPayload.prototype.setBlock = function(value) {
  jspb.Message.setOneofWrapperField(this, 2, proto.TurtleToTurtle.BlockChainPayload.oneofGroups_[0], value);
};


proto.TurtleToTurtle.BlockChainPayload.prototype.clearBlock = function() {
  this.setBlock(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.TurtleToTurtle.BlockChainPayload.prototype.hasBlock = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional TurtleCoin.TurtleTransaction transaction = 3;
 * @return {?proto.TurtleToTurtle.TurtleCoin.TurtleTransaction}
 */
proto.TurtleToTurtle.BlockChainPayload.prototype.getTransaction = function() {
  return /** @type{?proto.TurtleToTurtle.TurtleCoin.TurtleTransaction} */ (
    jspb.Message.getWrapperField(this, proto.TurtleToTurtle.TurtleCoin.TurtleTransaction, 3));
};


/** @param {?proto.TurtleToTurtle.TurtleCoin.TurtleTransaction|undefined} value */
proto.TurtleToTurtle.BlockChainPayload.prototype.setTransaction = function(value) {
  jspb.Message.setOneofWrapperField(this, 3, proto.TurtleToTurtle.BlockChainPayload.oneofGroups_[0], value);
};


proto.TurtleToTurtle.BlockChainPayload.prototype.clearTransaction = function() {
  this.setTransaction(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.TurtleToTurtle.BlockChainPayload.prototype.hasTransaction = function() {
  return jspb.Message.getField(this, 3) != null;
};


