// Copyright (c) 2018, The TurtleCoin Developers
// 
// Please see the included LICENSE file for more information.

/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.TurtleToTurtle.T2TCandidateList');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.TurtleToTurtle.T2TCandidate');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.TurtleToTurtle.T2TCandidateList = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.TurtleToTurtle.T2TCandidateList.repeatedFields_, null);
};
goog.inherits(proto.TurtleToTurtle.T2TCandidateList, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.TurtleToTurtle.T2TCandidateList.displayName = 'proto.TurtleToTurtle.T2TCandidateList';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.TurtleToTurtle.T2TCandidateList.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.TurtleToTurtle.T2TCandidateList.prototype.toObject = function(opt_includeInstance) {
  return proto.TurtleToTurtle.T2TCandidateList.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.TurtleToTurtle.T2TCandidateList} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.TurtleToTurtle.T2TCandidateList.toObject = function(includeInstance, msg) {
  var f, obj = {
    candidateList: jspb.Message.toObjectList(msg.getCandidateList(),
    proto.TurtleToTurtle.T2TCandidate.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.TurtleToTurtle.T2TCandidateList}
 */
proto.TurtleToTurtle.T2TCandidateList.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.TurtleToTurtle.T2TCandidateList;
  return proto.TurtleToTurtle.T2TCandidateList.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.TurtleToTurtle.T2TCandidateList} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.TurtleToTurtle.T2TCandidateList}
 */
proto.TurtleToTurtle.T2TCandidateList.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.TurtleToTurtle.T2TCandidate;
      reader.readMessage(value,proto.TurtleToTurtle.T2TCandidate.deserializeBinaryFromReader);
      msg.addCandidate(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.TurtleToTurtle.T2TCandidateList.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.TurtleToTurtle.T2TCandidateList.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.TurtleToTurtle.T2TCandidateList} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.TurtleToTurtle.T2TCandidateList.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCandidateList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.TurtleToTurtle.T2TCandidate.serializeBinaryToWriter
    );
  }
};


/**
 * repeated T2TCandidate candidate = 1;
 * @return {!Array<!proto.TurtleToTurtle.T2TCandidate>}
 */
proto.TurtleToTurtle.T2TCandidateList.prototype.getCandidateList = function() {
  return /** @type{!Array<!proto.TurtleToTurtle.T2TCandidate>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.TurtleToTurtle.T2TCandidate, 1));
};


/** @param {!Array<!proto.TurtleToTurtle.T2TCandidate>} value */
proto.TurtleToTurtle.T2TCandidateList.prototype.setCandidateList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.TurtleToTurtle.T2TCandidate=} opt_value
 * @param {number=} opt_index
 * @return {!proto.TurtleToTurtle.T2TCandidate}
 */
proto.TurtleToTurtle.T2TCandidateList.prototype.addCandidate = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.TurtleToTurtle.T2TCandidate, opt_index);
};


proto.TurtleToTurtle.T2TCandidateList.prototype.clearCandidateList = function() {
  this.setCandidateList([]);
};


