<?php
// Copyright (c) 2018, The TurtleCoin Developers
// 
// Please see the included LICENSE file for more information.


# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TurtleToTurtle.proto

namespace TurtleToTurtle;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>TurtleToTurtle.T2TCandidate</code>
 */
class T2TCandidate extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string peerId = 1;</code>
     */
    private $peerId = '';
    /**
     * Generated from protobuf field <code>uint32 version = 2;</code>
     */
    private $version = 0;
    /**
     * Generated from protobuf field <code>uint32 ipV4Address = 3;</code>
     */
    private $ipV4Address = 0;
    /**
     * Generated from protobuf field <code>string ipV6Address = 4;</code>
     */
    private $ipV6Address = '';
    /**
     * Generated from protobuf field <code>uint32 port = 5;</code>
     */
    private $port = 0;
    /**
     * Generated from protobuf field <code>uint32 ttl = 6;</code>
     */
    private $ttl = 0;
    /**
     * Generated from protobuf field <code>.TurtleToTurtle.T2TNodeCapability capability = 7;</code>
     */
    private $capability = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $peerId
     *     @type int $version
     *     @type int $ipV4Address
     *     @type string $ipV6Address
     *     @type int $port
     *     @type int $ttl
     *     @type \TurtleToTurtle\T2TNodeCapability $capability
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\TurtleToTurtle::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string peerId = 1;</code>
     * @return string
     */
    public function getPeerId()
    {
        return $this->peerId;
    }

    /**
     * Generated from protobuf field <code>string peerId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPeerId($var)
    {
        GPBUtil::checkString($var, True);
        $this->peerId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 version = 2;</code>
     * @return int
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * Generated from protobuf field <code>uint32 version = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkUint32($var);
        $this->version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 ipV4Address = 3;</code>
     * @return int
     */
    public function getIpV4Address()
    {
        return $this->ipV4Address;
    }

    /**
     * Generated from protobuf field <code>uint32 ipV4Address = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setIpV4Address($var)
    {
        GPBUtil::checkUint32($var);
        $this->ipV4Address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ipV6Address = 4;</code>
     * @return string
     */
    public function getIpV6Address()
    {
        return $this->ipV6Address;
    }

    /**
     * Generated from protobuf field <code>string ipV6Address = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setIpV6Address($var)
    {
        GPBUtil::checkString($var, True);
        $this->ipV6Address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 port = 5;</code>
     * @return int
     */
    public function getPort()
    {
        return $this->port;
    }

    /**
     * Generated from protobuf field <code>uint32 port = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setPort($var)
    {
        GPBUtil::checkUint32($var);
        $this->port = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 ttl = 6;</code>
     * @return int
     */
    public function getTtl()
    {
        return $this->ttl;
    }

    /**
     * Generated from protobuf field <code>uint32 ttl = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setTtl($var)
    {
        GPBUtil::checkUint32($var);
        $this->ttl = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.TurtleToTurtle.T2TNodeCapability capability = 7;</code>
     * @return \TurtleToTurtle\T2TNodeCapability
     */
    public function getCapability()
    {
        return $this->capability;
    }

    /**
     * Generated from protobuf field <code>.TurtleToTurtle.T2TNodeCapability capability = 7;</code>
     * @param \TurtleToTurtle\T2TNodeCapability $var
     * @return $this
     */
    public function setCapability($var)
    {
        GPBUtil::checkMessage($var, \TurtleToTurtle\T2TNodeCapability::class);
        $this->capability = $var;

        return $this;
    }

}

