<?php
// Copyright (c) 2018, The TurtleCoin Developers
//
// Please see the included LICENSE file for more information.


# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TurtleToTurtle.proto

namespace TurtleToTurtle;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>TurtleToTurtle.T2TCandidateList</code>
 */
class T2TCandidateList extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .TurtleToTurtle.T2TCandidate candidate = 1;</code>
     */
    private $candidate;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \TurtleToTurtle\T2TCandidate[]|\Google\Protobuf\Internal\RepeatedField $candidate
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\TurtleToTurtle::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .TurtleToTurtle.T2TCandidate candidate = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCandidate()
    {
        return $this->candidate;
    }

    /**
     * Generated from protobuf field <code>repeated .TurtleToTurtle.T2TCandidate candidate = 1;</code>
     * @param \TurtleToTurtle\T2TCandidate[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCandidate($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \TurtleToTurtle\T2TCandidate::class);
        $this->candidate = $arr;

        return $this;
    }

}

