<?php
// Copyright (c) 2018, The TurtleCoin Developers
// 
// Please see the included LICENSE file for more information.

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Turtle2Turtle.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>T2TDatagram</code>
 */
class T2TDatagram extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 p2pNetworkId = 1;</code>
     */
    private $p2pNetworkId = 0;
    /**
     * Generated from protobuf field <code>uint32 version = 2;</code>
     */
    private $version = 0;
    /**
     * Generated from protobuf field <code>string peerId = 3;</code>
     */
    private $peerId = '';
    protected $dataPayload;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $p2pNetworkId
     *     @type int $version
     *     @type string $peerId
     *     @type \T2TCandidateList $t2tCandidateList
     *     @type \T2TCandidateListRequest $t2tCandidateListRequest
     *     @type \BlockChainPayload $blockChainPayload
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Turtle2Turtle::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 p2pNetworkId = 1;</code>
     * @return int
     */
    public function getP2PNetworkId()
    {
        return $this->p2pNetworkId;
    }

    /**
     * Generated from protobuf field <code>uint32 p2pNetworkId = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setP2PNetworkId($var)
    {
        GPBUtil::checkUint32($var);
        $this->p2pNetworkId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 version = 2;</code>
     * @return int
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * Generated from protobuf field <code>uint32 version = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkUint32($var);
        $this->version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string peerId = 3;</code>
     * @return string
     */
    public function getPeerId()
    {
        return $this->peerId;
    }

    /**
     * Generated from protobuf field <code>string peerId = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setPeerId($var)
    {
        GPBUtil::checkString($var, True);
        $this->peerId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.T2TCandidateList t2tCandidateList = 4;</code>
     * @return \T2TCandidateList
     */
    public function getT2TCandidateList()
    {
        return $this->readOneof(4);
    }

    /**
     * Generated from protobuf field <code>.T2TCandidateList t2tCandidateList = 4;</code>
     * @param \T2TCandidateList $var
     * @return $this
     */
    public function setT2TCandidateList($var)
    {
        GPBUtil::checkMessage($var, \T2TCandidateList::class);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.T2TCandidateListRequest t2tCandidateListRequest = 5;</code>
     * @return \T2TCandidateListRequest
     */
    public function getT2TCandidateListRequest()
    {
        return $this->readOneof(5);
    }

    /**
     * Generated from protobuf field <code>.T2TCandidateListRequest t2tCandidateListRequest = 5;</code>
     * @param \T2TCandidateListRequest $var
     * @return $this
     */
    public function setT2TCandidateListRequest($var)
    {
        GPBUtil::checkMessage($var, \T2TCandidateListRequest::class);
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.BlockChainPayload blockChainPayload = 6;</code>
     * @return \BlockChainPayload
     */
    public function getBlockChainPayload()
    {
        return $this->readOneof(6);
    }

    /**
     * Generated from protobuf field <code>.BlockChainPayload blockChainPayload = 6;</code>
     * @param \BlockChainPayload $var
     * @return $this
     */
    public function setBlockChainPayload($var)
    {
        GPBUtil::checkMessage($var, \BlockChainPayload::class);
        $this->writeOneof(6, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getDataPayload()
    {
        return $this->whichOneof("dataPayload");
    }

}

